package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
	"github.com/thollingworth/graphql-demo/multiple-serve/opcua-proxy/domain"
)

// Current is the resolver for the current field.
func (r *equipmentPropertyResolver) Current(ctx context.Context, obj *domain.EquipmentProperty, federationRequires map[string]interface{}) (*domain.Tag, error) {
	if obj == nil {
		return nil, fmt.Errorf("EquipmentProperty is nil")
	}
	addressRaw, ok := federationRequires["address"]
	if !ok {
		return nil, fmt.Errorf("address not defined")
	}

	address, ok := addressRaw.(string)
	if !ok {
		return nil, fmt.Errorf("address not a string")
	}

	return r.Client.Read(ctx, address)
}

// ReadTag is the resolver for the readTag field.
func (r *queryResolver) ReadTag(ctx context.Context, address string) (*domain.Tag, error) {
	return r.Client.Read(ctx, address)
}

// QueryTag is the resolver for the queryTag field.
func (r *queryResolver) QueryTag(ctx context.Context, addresses []string) ([]*domain.Tag, error) {
	result := make([]*domain.Tag, len(addresses))
	var err error
	for i, address := range addresses {
		result[i], err = r.Client.Read(ctx, address)
		if err != nil {
			graphql.AddErrorf(ctx, "Error %s", err.Error())
		}
	}
	return result, nil
}

// EquipmentProperty returns EquipmentPropertyResolver implementation.
func (r *Resolver) EquipmentProperty() EquipmentPropertyResolver {
	return &equipmentPropertyResolver{r}
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type equipmentPropertyResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
