// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Equipment struct {
	ID          string               `json:"id"`
	Name        string               `json:"name"`
	Description *string              `json:"description,omitempty"`
	Properties  []*EquipmentProperty `json:"properties"`
}

type EquipmentProperty struct {
	ID          string     `json:"id"`
	Description string     `json:"description"`
	Address     *string    `json:"address,omitempty"`
	Equipment   *Equipment `json:"equipment"`
}

type EquipmentRef struct {
	ID string `json:"id"`
}

type FilterEquipmentProperty struct {
	ID        *string       `json:"id,omitempty"`
	Equipment *EquipmentRef `json:"equipment,omitempty"`
}

type Mutation struct {
}

type NewEquipment struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type NewEquipmentProperty struct {
	ID          string        `json:"id"`
	Description *string       `json:"description,omitempty"`
	Address     *string       `json:"address,omitempty"`
	Equipment   *EquipmentRef `json:"equipment"`
}

type Query struct {
}
