// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package domain

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type DateTimeRange struct {
	Max time.Time `json:"max"`
	Min time.Time `json:"min"`
}

type EquipmentProperty struct {
	ID      string     `json:"id"`
	Address *string    `json:"address,omitempty"`
	History []*History `json:"history,omitempty"`
}

func (EquipmentProperty) IsEntity() {}

type FilterHistory struct {
	Timestamp *DateTimeRange `json:"timestamp,omitempty"`
	Address   *string        `json:"address,omitempty"`
}

type History struct {
	Address   string    `json:"address"`
	Timestamp time.Time `json:"timestamp"`
	Value     string    `json:"value"`
	Datatype  DataType  `json:"datatype"`
}

type Mutation struct {
}

type NewHistory struct {
	Address   string    `json:"address"`
	Timestamp time.Time `json:"timestamp"`
	Value     string    `json:"value"`
	Datatype  DataType  `json:"datatype"`
}

type Query struct {
}

type DataType string

const (
	DataTypeString  DataType = "STRING"
	DataTypeInt     DataType = "INT"
	DataTypeFloat   DataType = "FLOAT"
	DataTypeUnknown DataType = "UNKNOWN"
	DataTypeBoolean DataType = "BOOLEAN"
	DataTypeOther   DataType = "OTHER"
)

var AllDataType = []DataType{
	DataTypeString,
	DataTypeInt,
	DataTypeFloat,
	DataTypeUnknown,
	DataTypeBoolean,
	DataTypeOther,
}

func (e DataType) IsValid() bool {
	switch e {
	case DataTypeString, DataTypeInt, DataTypeFloat, DataTypeUnknown, DataTypeBoolean, DataTypeOther:
		return true
	}
	return false
}

func (e DataType) String() string {
	return string(e)
}

func (e *DataType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DataType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DataType", str)
	}
	return nil
}

func (e DataType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
