// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package domain

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type DateTimeRange struct {
	Max time.Time `json:"max"`
	Min time.Time `json:"min"`
}

type EquipmentProperty struct {
	Iid     string     `json:"iid"`
	Address *string    `json:"address,omitempty"`
	History []*History `json:"history,omitempty"`
}

func (EquipmentProperty) IsEntity() {}

type FilterHistory struct {
	Timestamp *DateTimeRange `json:"timestamp,omitempty"`
	Address   *string        `json:"address,omitempty"`
}

type History struct {
	Address   string        `json:"address"`
	Timestamp time.Time     `json:"timestamp"`
	Value     string        `json:"value"`
	Datatype  OpcUaDataType `json:"datatype"`
}

type Mutation struct {
}

type NewHistory struct {
	Address   string        `json:"address"`
	Timestamp time.Time     `json:"timestamp"`
	Value     string        `json:"value"`
	Datatype  OpcUaDataType `json:"datatype"`
}

type Query struct {
}

type OpcUaDataType string

const (
	OpcUaDataTypeString  OpcUaDataType = "STRING"
	OpcUaDataTypeInt     OpcUaDataType = "INT"
	OpcUaDataTypeFloat   OpcUaDataType = "FLOAT"
	OpcUaDataTypeUnknown OpcUaDataType = "UNKNOWN"
	OpcUaDataTypeBoolean OpcUaDataType = "BOOLEAN"
	OpcUaDataTypeOther   OpcUaDataType = "OTHER"
)

var AllOpcUaDataType = []OpcUaDataType{
	OpcUaDataTypeString,
	OpcUaDataTypeInt,
	OpcUaDataTypeFloat,
	OpcUaDataTypeUnknown,
	OpcUaDataTypeBoolean,
	OpcUaDataTypeOther,
}

func (e OpcUaDataType) IsValid() bool {
	switch e {
	case OpcUaDataTypeString, OpcUaDataTypeInt, OpcUaDataTypeFloat, OpcUaDataTypeUnknown, OpcUaDataTypeBoolean, OpcUaDataTypeOther:
		return true
	}
	return false
}

func (e OpcUaDataType) String() string {
	return string(e)
}

func (e *OpcUaDataType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OpcUaDataType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OpcUaDataType", str)
	}
	return nil
}

func (e OpcUaDataType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
