package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"
	"fmt"

	"github.com/tomhollingworth/graphql-demo/multiple-serve/sql-proxy/graph/model"
)

// FindEquipmentByID is the resolver for the findEquipmentByID field.
func (r *entityResolver) FindEquipmentByID(ctx context.Context, id string) (*model.Equipment, error) {
	rows, err := db.Query("SELECT id, name, description FROM equipment WHERE id = $1", id)
	defer rows.Close()

	if err != nil {
		return nil, err
	}

	for rows.Next() {
		e := model.Equipment{}
		if err := rows.Scan(&e.ID, &e.Name, &e.Description); err != nil {
			fmt.Printf("failed to scan equipment row: %v\n", err)
			continue
		}

		return &e, nil
	}
	return nil, fmt.Errorf("equipment with id %s does not exist", id)
}

// FindEquipmentPropertyByID is the resolver for the findEquipmentPropertyByID field.
func (r *entityResolver) FindEquipmentPropertyByID(ctx context.Context, id string) (*model.EquipmentProperty, error) {
	rows, err := db.Query("SELECT id, description, address FROM equipment_property WHERE id = $1", id)
	defer rows.Close()

	if err != nil {
		return nil, err
	}

	for rows.Next() {
		ep := model.EquipmentProperty{}
		err := rows.Scan(&ep.ID, &ep.Description, &ep.Address)
		return &ep, err
	}
	return nil, err
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
