package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"
	"fmt"

	"github.com/thollingworth/graphql-demo/multiple-serve/kepware-proxy/domain"
)

// FindEquipmentPropertyByID is the resolver for the findEquipmentPropertyByID field.
func (r *entityResolver) FindEquipmentPropertyByID(ctx context.Context, id string) (*domain.EquipmentProperty, error) {
	panic(fmt.Errorf("not implemented: FindEquipmentPropertyByID - findEquipmentPropertyByID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
