package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/thollingworth/graphql-demo/multiple-serve/kepware-proxy/domain"
)

// ReadTag is the resolver for the readTag field.
func (r *queryResolver) ReadTag(ctx context.Context, address string) (*domain.Tag, error) {
	return r.Client.Read(ctx, address)
}

// QueryTag is the resolver for the queryTag field.
func (r *queryResolver) QueryTag(ctx context.Context, addresses []string) ([]*domain.Tag, error) {
	result := make([]*domain.Tag, len(addresses))
	var err error
	for i, address := range addresses {
		result[i], err = r.Client.Read(ctx, address)
		if err != nil {
			graphql.AddErrorf(ctx, "Error %s", err.Error())
		}
	}
	return result, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
